package p002;

/*
*Even Fibonacci numbers
*Problem 2
*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
*
*1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
*By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*
*/

import java.util.ArrayList;
import java.util.Collections;

public class Main {
    public static void main(String[] args) {
        long sum = 2;
        int i = 2;
        ArrayList<Long> fibonacci = new ArrayList<>();
        fibonacci.add(0, (long) 1);
        fibonacci.add(1, (long) 2);

        while(true){
            long myValue = fibonacci.get(i-1)+fibonacci.get(i-2);
            if(myValue >= 4000000)
                break;
            if(myValue % 2 == 0)
                sum += myValue;
            fibonacci.add(i,myValue);
            i++;
        }

        System.out.println(sum);


    }
}
